### ISSUE TITLE
Error when using middleman 4.0.0.rc.1

### ISSUE THREAD

**Issue by craigmdennis** [middleman-contrib/middleman-deploy#100]
I've got my Gem pointing to master but still getting the following errors

```
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/configuration.rb:75:in `define_setting': Setting method doesn't exist (RuntimeError)
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/configuration.rb:37:in `[]='
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/configuration.rb:46:in `method_missing'
	from /Users/craigmdennis/Sites/test/config.rb:51:in `block in evaluate_configuration!'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/extension.rb:367:in `setup_options'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/extension.rb:294:in `initialize'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/middleman-deploy-243ab38b0889/lib/middleman-deploy/extension.rb:31:in `initialize'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/extension_manager.rb:64:in `new'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/extension_manager.rb:64:in `activate'
	from /Users/craigmdennis/Sites/test/config.rb:50:in `evaluate_configuration!'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/application.rb:290:in `instance_eval'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/application.rb:290:in `evaluate_configuration!'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/application.rb:266:in `start_lifecycle'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/application.rb:254:in `initialize'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/preview_server.rb:107:in `new'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/preview_server.rb:107:in `new_app'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.rc.1/lib/middleman-core/preview_server.rb:27:in `start'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-cli-4.0.0.rc.1/lib/middleman-cli/server.rb:67:in `server'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-cli-4.0.0.rc.1/bin/middleman:23:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.0/bin/middleman:23:in `load'
	from /usr/local/var/rbenv/versions/2.2.0/bin/middleman:23:in `<main>'
```

**Comment by mojavelinux** [comment]
You need to change `method` to `deploy_method`.

Example:

```ruby
activate :deploy do |deploy|
  deploy.deploy_method = :git
end
```

You also need to be using the pre release version. https://rubygems.org/gems/middleman-deploy/versions/2.0.0.pre.alpha

**Comment by mojavelinux** [comment]
(It looks like you are using a development version, which will work to, but just to be sure I mentioned it).
