### ISSUE TITLE
The usage of "ptools" seems to break the "build" function of middleman on Windows

### ISSUE THREAD

**Issue by whitetrefoil** [middleman-contrib/middleman-deploy#62]
My ruby skill is not good enough so I came here to look for help.

I'm now using `middleman-deploy (0.2.3)` with `middleman (3.3.2)` & `ptools (1.2.4-x86-mingw32)`.

When trying to build the console throws:

```
E:/usr/local/Ruby/lib/ruby/2.0.0/pathname.rb:47:in `[]': no implicit conversion from nil to integer (TypeError)
        from E:/usr/local/Ruby/lib/ruby/2.0.0/pathname.rb:47:in `chop_basename'
        from E:/usr/local/Ruby/lib/ruby/2.0.0/pathname.rb:102:in `cleanpath_aggressive'
        from E:/usr/local/Ruby/lib/ruby/2.0.0/pathname.rb:90:in `cleanpath'
        from E:/usr/local/Ruby/lib/ruby/2.0.0/pathname.rb:486:in `relative_path_from'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.2/lib/middleman-core/cli/build.rb:193:in `execute!'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.2/lib/middleman-core/cli/build.rb:128:in `invoke!'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.2/lib/middleman-core/cli/build.rb:70:in `build'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.2/lib/middleman-core/cli.rb:76:in `method_missing'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.2/lib/middleman-core/cli.rb:22:in `start'
        from E:/usr/local/Ruby/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.2/bin/middleman:18:in `<top (required)>'
        from E:/usr/local/Ruby/bin/middleman:23:in `load'
        from E:/usr/local/Ruby/bin/middleman:23:in `<main>'
```

I traced to `E:/usr/local/Ruby/lib/ruby/2.0.0/pathname.rb:43`:

``` ruby
base = File.basename(path)
```

And at the **final moment** between crach, the result of `File.basename` became wired.

Before required `ptools`, `File.basename 'E:/'` returns `"/"` and everything was good.

After required `ptools`, `File.basename 'E:/'` returns `"E:\\"`, then cause the cause the following codes crashed:

``` ruby
    if /\A#{SEPARATOR_PAT}?\z/o =~ base
      return nil
    else
      return path[0, path.rindex(base)], base
    end
```

I know nor whether this is a bug or a 'by design' for `ptools`, nor whether this is expected for `middleman-deploy`, nor whether there will be another solution to get it work.  Is there anybody can help?

Thanks

**Comment by djberg96** [comment]
Is this still a problem since I've update pathname2?

**Comment by djberg96** [comment]
@whitetrefoil Any luck?

**Comment by whitetrefoil** [comment]
@djberg96 oops... Sorry, I didn't see your previous message.  I haven't written ruby for years, and I can't remember details of this issue. I need some time to catch up.

I guess we can close this issue.  If there's still problem we can just reopen it.😄
