### ISSUE TITLE
Deploy error in Windows 8.1

### ISSUE THREAD

**Issue by ivycheung** [middleman-contrib/middleman-deploy#89]
I added the gem and added activate :deploy (+ configs) for FTP upload.

When I run `middleman deploy` (or with bundle exec), I get the following error. Not sure where to start with this one. Any help would be appreciated.

Windows 8.1 64-bits, Ruby 2.1.0.

c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.10/lib/m
iddleman-more/core_extensions/default_helpers.rb:7:in `<top (required)>': uninit
ialized constant Padrino::Helpers::OutputHelpers (NameError)
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core
-3.3.10/lib/middleman-core/core_extensions.rb:30:in `require'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core
-3.3.10/lib/middleman-core/core_extensions.rb:30:in `<top (required)>'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core
-3.3.10/lib/middleman-core/application.rb:24:in `require'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core
-3.3.10/lib/middleman-core/application.rb:24:in `<top (required)>'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-depl
oy-1.0.0/lib/middleman-deploy/commands.rb:62:in `deploy_options'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-depl
oy-1.0.0/lib/middleman-deploy/commands.rb:36:in `build_before'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-depl
oy-1.0.0/lib/middleman-deploy/commands.rb:29:in `deploy'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/li
b/thor/command.rb:27:in `run'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/li
b/thor/invocation.rb:126:in `invoke_command'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/li
b/thor.rb:359:in `dispatch'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/li
b/thor/base.rb:440:in `start'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core
-3.3.10/lib/middleman-core/cli.rb:72:in `method_missing'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/li
b/thor/command.rb:29:in `run'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/li
b/thor/command.rb:126:in `run'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/li
b/thor/invocation.rb:126:in `invoke_command'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/li
b/thor.rb:359:in `dispatch'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/li
b/thor/base.rb:440:in `start'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core
-3.3.10/lib/middleman-core/cli.rb:20:in `start'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/middleman-core
-3.3.10/bin/middleman:18:in `<top (required)>'
        from c:/RailsInstaller/Ruby2.1.0/bin/middleman:23:in `load'
        from c:/RailsInstaller/Ruby2.1.0/bin/middleman:23:in `<main>'

**Comment by angeliquejw** [comment]
Same issue in Windows 7.

**Comment by cfabroni** [comment]
Same issue here, in Windows 8.1 x64

**Comment by gazialankus** [comment]
+1 here. Windows 8.1 x64. Can't even run `bundle exec middleman server` or `bundle exec middleman build`, I just get the error above.

**Comment by AbelToy** [comment]
Same here, with deploy activated I can't run `middleman server` or `middleman build`, and obviously can't deploy either, on Windows 7.

**Comment by yeltsin** [comment]
+1 Windows 10 x64

**Comment by petko** [comment]
Any progress on this one? It doesn't work on Windows 7 x64 too..

**Comment by guidopontet** [comment]
Don't work on Windows 10. Can't even run bundle exec middleman server:

```
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Traceback (most recent call last):
        23: from C:/Ruby25/bin/middleman:23:in `<main>'
        22: from C:/Ruby25/bin/middleman:23:in `load'
        21: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/middleman-cli-4.3.4/bin/middleman:49:in `<top (required)>'
        20: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/middleman-cli-4.3.4/bin/middleman:49:in `new'
        19: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/application.rb:280:in `initialize'
        18: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
        17: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        16: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        15: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        14: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/callback_manager.rb:57:in `execute'
        13: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
        12: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        11: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
        10: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/callback_manager.rb:57:in `block in execute'
         9: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
         8: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/extension_manager.rb:20:in `block (2 levels) in initialize'
         7: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/extension_manager.rb:28:in `auto_activate'
         6: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/extensions.rb:117:in `auto_activate'
         5: from C:/Ruby25/lib/ruby/2.5.0/set.rb:338:in `each'
         4: from C:/Ruby25/lib/ruby/2.5.0/set.rb:338:in `each_key'
         3: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/extensions.rb:120:in `block in auto_activate'
         2: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/extension_manager.rb:66:in `activate'
         1: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/extension_manager.rb:66:in `new'
C:/Ruby25/lib/ruby/gems/2.5.0/gems/middleman-core-4.3.4/lib/middleman-core/core_extensions/default_helpers.rb:36:in `initialize': uninitialized constant Padrino::Helpers::TagHelpers (NameError)
Did you mean?  Padrino::Helpers
```
